# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherclass',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='level',
            field=models.CharField(choices=[('Primary one', 'Primary one'), ('Primary Two', 'Primary Two'), ('Primary Three', 'Primary Three')], default='Primary one', max_length=20),
        ),
    ]
