# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0002_auto_20160927_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclass',
            name='name',
            field=models.CharField(default='Class Name', max_length=50),
            preserve_default=False,
        ),
    ]
